[workspace]
resolver = "2"
members = [
    "crates/save",
    "crates/wayfarer",
]


[workspace.package]
version = "0.4.0"
edition = "2021"
license-file = "LICENSE"


[profile.release]
opt-level = 3
codegen-units = 4
lto = "fat"
panic = "abort"
strip = "debuginfo"
