[package]
name = "wayfarer"
version.workspace = true
edition.workspace = true
license-file.workspace = true


[dependencies]
anyhow = "1.0"

[dependencies.clap]
version = "4.3"
features = ["derive"]

[dependencies.jrny-save]
version = "0.1"
path = "../save"

[dependencies.notify]
version = "6.0"
optional = true


[features]
default = ["watch"]
watch = ["dep:notify"]
