[package]
name = "jrny-save"
version.workspace = true
edition.workspace = true
license-file.workspace = true


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
binrw = "0.11"
chrono = "0.4"
urlencoding = "2.1"
substring = "1.4"
